name: Test ARC Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Hello from runner
        run: echo "Hello! I am running inside Kubernetes cluster!"

      - name: Check hostname
        run: hostname

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mkdir -p $HOME/bin
          mv kubectl $HOME/bin/kubectl
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Check kubectl
        run: kubectl version --client